import turtle
ourScreen = turtle.Screen()
ourTurtle = turtle.Turtle()



ourTurtle.color("brown")

ourTurtle.color("blue")
ourTurtle.color("red")
ourTurtle.color("yellow")
ourTurtle.color("purple")
ourTurtle.color("pink")
ourTurtle.color("black")
ourTurtle.color("brown")
ourTurtle.color("blue")
ourTurtle.color("red")
ourTurtle.color("yellow")
ourTurtle.color("purple")
ourTurtle.color("pink")
ourTurtle.color("black")
ourTurtle.pencolor("blue")
ourTurtle.fd(100)
ourTurtle.lt(90)
ourTurtle.fd(100)
ourTurtle.lt(90)
ourTurtle.fd(100)
ourTurtle.lt(90)
ourTurtle.fd(100)
ourTurtle.rt(90)
ourTurtle.fd(100)
ourTurtle.rt(90)
ourTurtle.fd(100)
ourTurtle.rt(90)
ourTurtle.fd(100)
ourTurtle.lt(90)
ourTurtle.fd(100)
ourTurtle.rt(90)
ourTurtle.fd(100)
ourTurtle.lt(180)
ourTurtle.fd(200)
ourTurtle.lt(90)
ourTurtle.fd(100)
ourTurtle.rt(90)
ourTurtle.fd(110)
ourTurtle.rt(180)
ourTurtle.fd(200)
ourTurtle.fd(110)
ourTurtle.rt(90)
ourTurtle.color("green")
ourScreen.Backgroundcolor("red")
ourTurtle.reset()
ourTurtle.fd(100)
ourTurtle.lt(90)
ourTurtle.fd(100)
ourTurtle.lt(90)
ourTurtle.fd(100)
ourTurtle.lt(90)
ourTurtle.fd(100)
ourTurtle.shape("turtle")
ourTurtle.fd(100)
ourTurtle.color("yellow")
ourScreen.Backgroundcolor("blue")
ourTurtle.lt(90)
ourTurtle.fd(100)

ourScreen.exitonclick()



ourScreen.exitonclick()
